# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::905221885307:role/eksctl-17d-nodegroup-ng-dd455ccb-NodeInstanceRole-1ORVv5KmPaVP
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::905221885307:user/madhu
      username: madhu
      groups:
        - system:authenticated

    - userarn: arn:aws:iam::905221885307:user/kiran
      username: kiran
      groups:
        - system:authenticated
        
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-22T13:11:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "15957"
  uid: b015a7de-a12b-4c32-a323-42e078d35d6a
