
---
apiVersion: v1
kind: Pod 
metadata:
  name: facebooksecret
  labels:
    app: facebook
spec:
  containers:
  - name: facebooksecret 
    image: nginx:latest
    ports:
    - containerPort: 80

    envFrom:
    - secretRef:
        name: fb-secret